name: Run Python tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio httpx python-dotenv

      - name: Run tests
        env:
          GREPTILE_API_KEY: test_api_key
          GITHUB_TOKEN: test_github_token
          GREPTILE_BASE_URL: https://api.greptile.test/v2
        run: |
          pytest src/tests --maxfail=3 --disable-warnings -v